export { default as logo } from "../Assets/Images/logo.png";
export { default as searchIcon } from "../Assets/Images/search.png";
export { default as OutfitterBanner } from "../Assets/Images/Outfitters-Banner.jpg";
export { default as product1 } from "../Assets/Images/product1.jpg";
export { default as map } from "../Assets/Images/map.png";
export { default as login } from "../Assets/Images/login.png";
export { default as signup } from "../Assets/Images/signup.jpg";
export { default as hero } from "../Assets/Images/hero.jpg";
export { default as teacher } from "../Assets/Images/teacher.jpg";
export { default as heroBg } from "../Assets/Images/heroBg.jpg";
export { default as search } from "../Assets/Images/search.jpg";
export { default as about } from "../Assets/Images/about-us.jpg";
export { default as user } from "../Assets/Images/user.jfif";
export { default as Logoo } from "../Assets/Images/Logoo.png";
export { default as about1 } from "../Assets/Images/about-us-page.png";
export { default as about2 } from "../Assets/Images/about-us-page2.png";
export { default as mansoorImg } from "../Assets/Images/mansoor.jfif";
export { default as tabishImg } from "../Assets/Images/Tabish .jpeg";
export { default as anasImg } from "../Assets/Images/Anas Tahir.jpeg";
export { default as AhmedImg } from "../Assets/Images/Ahmed Asif.jpeg";
export { default as danialImg } from "../Assets/Images/Syed Danyal Ahmed.jpeg";
export { default as footerCity } from "../Assets/Images/footer-city.svg";
export { default as HeroImage } from "../Assets/Images/hero-section.png";
export { default as studentImg } from "../Assets/Images/studentImg.png";
